# Generated by Django 6.0.1 on 2026-05-07 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_app', '0003_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_employee',
            field=models.BooleanField(default=False, verbose_name='Сотрудник'),
        ),
    ]
