# Generated by Django 6.0.1 on 2026-09-06 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_app', '0006_partner_service_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='certificate',
            field=models.TextField(blank=True, verbose_name='Сертификат'),
        ),
    ]
